overblog_graphql_endpoint:
    path: /graphql
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"

overblog_graphql_batch_endpoint:
    path: /graphql/batch
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
        _format: "json"

overblog_graphql_multiple_endpoint:
    path: /graphql/{schemaName}
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"
    requirements:
        schemaName: '[^/]+'

overblog_graphql_batch_multiple_endpoint:
    path: /graphql/{schemaName}/batch
    defaults:
        _controller: Overblog\GraphQLBundle\Controller\GraphController::batchEndpointAction
        _format: "json"
    requirements:
        schemaName: '[^/]+'
