services:
    _defaults:
        autowire: true      # automatically injects dependencies in your services
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.
        public: false       # disallow fetch services directly from the container via $container->get()

    ####################################################################################################################
    # ADJUSTMENTS TO THE AUTO-WIRING
    ####################################################################################################################

    # When the service definition only contains arguments, you can omit the
    # 'arguments' key and define the arguments just below the service class

    # There are several implementations of this interface, so we need to choose one of them
    Acme\App\Infrastructure\Notification\Client\Email\SwiftMailer\Mapper\EmailMapper:
        class: Acme\App\Infrastructure\Notification\Client\Email\SwiftMailer\Mapper\SwiftEmailMapper

    Acme\App\Infrastructure\Notification\Client\Push\OneSignal\OneSignalClient:
        $appIDKey: '%notification.push.one_signal.app_id%'
        $restAPIKey: '%notification.push.one_signal.rest_api_key%'

    Acme\App\Infrastructure\Notification\Client\Sms\Twilio\TwilioClient:
        $countryCode: '%country%'
        $sender: '%notification.sms.sender%'
        $defaultDestination: '%notification.sms.default_destination%'

    Acme\App\Infrastructure\Notification\Strategy\Email\EmailNotificationStrategy:
        tags:
            - name: notification_strategy

    Acme\App\Infrastructure\Notification\Strategy\Push\PushNotificationStrategy:
        arguments:
            # There are several implementations of this interface, so we need to choose one of them
            $pushNotificationSettingsService: '@Acme\App\Infrastructure\Notification\Settings\PushNotificationSettingsService'
        tags:
            - name: notification_strategy

    Acme\App\Infrastructure\Notification\Strategy\Sms\SmsNotificationStrategy:
        arguments:
            # There are several implementations of this interface, so we need to choose one of them
            $smsNotificationSettingsService: '@Acme\App\Infrastructure\Notification\Settings\SmsNotificationSettingsService'
        tags:
            - name: notification_strategy

    MessageBird\Client:
        - '%notification.sms.message_bird.client.access_key%'

    Twilio\Rest\Client:
        - '%notification.sms.twilio.client.sid%'
        - '%notification.sms.twilio.client.token%'
