services:
    _defaults:
        autowire: true      # automatically injects dependencies in your services
        autoconfigure: true # automatically registers your services as commands, event subscribers, etc.
        public: false       # disallow fetch services directly from the container via $container->get()

    ####################################################################################################################
    # ADJUSTMENTS TO THE AUTO-WIRING
    ####################################################################################################################

    # When the service definition only contains arguments, you can omit the
    # 'arguments' key and define the arguments just below the service class

    # There are several implementations of this interface, so we need to choose one of them
    Acme\App\Core\Port\Persistence\KeyValueStorageInterface:
        class: Acme\App\Infrastructure\Persistence\Doctrine\KeyValueStorage

    Acme\App\Core\Port\Persistence\QueryServiceRouter:
        - '@Acme\App\Infrastructure\Persistence\Doctrine\DqlPersistenceService'
