# These lines define a route using YAML configuration. The controller used by
# the route (FrameworkBundle:Template:template) is a convenient shortcut when
# the template can be rendered without executing any logic in your own controller.
# See https://symfony.com/doc/current/cookbook/templating/render_without_controller.html

# We need to order the routes because of the matching order
# PostList must come before Post so the rss.xml is not confused with a post ID

website:
    resource: 'web/index.yaml'

# this route must be the last, its used to redirect any URL with a trailing slash that was not matched
redirect_url_with_trailing_slash:
    path: '{url_with_trailing_slash}'
    controller: Acme\App\Presentation\Web\Core\Component\BackslashRedirectController::removeTrailingSlash
    requirements:
        url_with_trailing_slash: '.*\/$'
